version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: app/Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock 
    ports:
      - "8020:8020"
    restart: unless-stopped

  ui:
    build:
      context: .
      dockerfile: ui/Dockerfile
    depends_on:
      - backend
    environment:
      - API_URL=http://backend:8020 
    ports:
      - "8501:8501"
    restart: unless-stopped
